# Generated by Django 5.0.1 on 2024-01-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=400)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
